### ISSUE TITLE
Twitter oauth1 doesn't work. 

### ISSUE THREAD

**Issue by danilke** [st4lk/django-rest-social-auth#72] opened 2018-12-10 15:12 UTC
Hello, I'm trying to log in with twitter oauth1, but I'm getting an error: 

```HTTPError at /api/login/social/token/
403 Client Error: Forbidden for url: https://api.twitter.com/oauth/request_token
```
https://github.com/python-social-auth/social-app-django/issues/164 - I think here is the reason.

**Comment by derek-adair** [comment] 2019-01-27 02:04
Works for me and is resolved by https://github.com/python-social-auth/social-app-django/issues/164

I'd suggest closing this one.

**Comment by st4lk** [comment] 2020-02-02 17:37
Since https://github.com/python-social-auth/social-app-django/issues/164 is closed and I can't reproduce it - I'm closing it.

**Closed by st4lk** 2020-02-02 17:37 UTC
