### ISSUE TITLE
Credentials issue

### ISSUE THREAD

**Issue by alexislg2** [st4lk/django-rest-social-auth#19] opened 2016-03-03 22:50 UTC
Hey,
thanks for that package first. I try to log through `/api/login/social/session/` as explained in the doc but I got the following error: `401 {"detail":"Authentication credentials were not provided."}`

I know it is due to django rest framework that is expecting some credentials but how am I supposed to handle that? I don't have credentials to provide because this is what the route is suppose to return me.

My settings look like this
```


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
    ),
}
```

**Comment by st4lk** [comment] 2016-03-04 07:37
Hi, Alexis!

Have you tried `/api/login/social/jwt/` url to login?

**Comment by alexislg2** [comment] 2016-03-04 10:40
Same behaviour on `/api/login/social/jwt/` 

If I remove the `REST_FRAMEWORK` from my settings.py I got `{"detail": "Not found."}`

**Comment by st4lk** [comment] 2016-03-04 11:01
The problem can be caused by invalid input data.

Please take a look at example project in this repo, does it work for you?

**Comment by alexislg2** [comment] 2016-03-04 12:49
OK problem was that I did not put the `social.backends.facebook.FacebookOAuth2` in `AUTHENTICATION_BACKENDS`

But new problem sorry... Now I got error 400 without error message. My payload is `provider` (`"facebook"`) and `code` that I get from here https://developers.facebook.com/tools/debug/accesstoken for the corresponding facebook app.

After some debugging I see that this Exception is thrown : https://github.com/st4lk/django-rest-social-auth/blob/master/rest_social_auth/views.py#L110

I guess this is because it cannot create new user (the access_token I provide in my payload is not linked with any user account so I expect it to create a new user)

**Comment by alexislg2** [comment] 2016-03-05 16:29
Could you please confirm me that this package should return JWT token just from a facebook access_token and create new user if no user exists with that facebook account?

This was not so clear for me in your documentation

**Comment by st4lk** [comment] 2016-03-06 14:41
The flow is the following:
1. Javascript get the code from facebook
2. Javascript POST this code to django application
3. django application exchange this code to access token (using this package). Then using this access token get user data (email) from facebook; get or create the user in database; generate jwt; return it
4. Later, javascript can use this token in requests (same as session id)

So you need to submit the code, not the access token.

I can suggest to read this [article](http://www.lexev.org/en/2015/oauth-step-step/). Two strategies of OAuth 2.0 are described there, and current project use "OAuth 2.0 with server". 

Please try the example project, does it works for you?

**Comment by alexislg2** [comment] 2016-03-06 16:40
OK thank you for these explanations. I think the problem comes from the
fact that I submit access_token ans I should send authorization code
instead. I'm using ng-cordova-oauth to get the access_token but this does
not provide the autorization code, I'll have a look at your website +
google thanks

**Comment by st4lk** [comment] 2016-04-02 21:56
Alexis,

have you solved the problem?

**Comment by alexislg2** [comment] 2016-04-02 21:59
Yes I'm using django-rest-framework-social-oauth2 that allows me to do what
I need. Thanks

Le sam. 2 avr. 2016 23:56, Alexey Evseev <notifications@github.com> a
écrit :

**Comment by st4lk** [comment] 2016-04-02 22:19
Ok, i think we can close the issue in that case.

**Closed by st4lk** 2016-04-02 22:19 UTC
