### ISSUE TITLE
we need django 2.0++ support

### ISSUE THREAD

**Issue by ultra2mh** [st4lk/django-rest-social-auth#61] opened 2018-03-18 05:39 UTC

**Comment by st4lk** [comment] 2018-03-20 04:24
Hi, will work on it soon

**Comment by yedengbp** [comment] 2018-04-19 22:32
@st4lk 
What are the main tasks to make it work with Django 2.0+?
I am trying to use it with 2.0+ now. I am wondering that if I can make a quick-and-dirty version for my own tests now.

**Comment by yedengbp** [comment] 2018-04-20 09:45
@st4lk  
Oh. That's cool. Thanks.

**Comment by st4lk** [comment] 2018-04-21 16:43
Closing as duplicate of #58

**Closed by st4lk** 2018-04-21 16:43 UTC
